[tool.poetry]
name = "users"
version = "0.1.0"
description = ""
authors = ["ITDevSuccess <raharisontsidiany@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
